name: Johan Dj√§ken
favicon: null
layout_spectrum: 0.28936
typography_spectrum: 0.8938090174924582
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#353535'
    - '#fefefe'
    - '#737373'
    - '#b6b6b6'
  brandStrength: 0.36915698065422475
  lightness: 0.12649325607344508
  saturation: 0.625
  rhythmicContrast: 0.7721700563561171
purpose: []
